# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "enki"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andy Triggs"]
  s.date = "2012-02-22"
  s.description = "TODO: longer description of your gem"
  s.email = "andy.triggs@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/assets/images/admin/flash_bg.gif",
    "app/assets/images/admin/future_bg.png",
    "app/assets/images/admin/gray_bg.gif",
    "app/assets/images/admin/new_button.png",
    "app/assets/images/admin/silver_bg.gif",
    "app/assets/images/admin/submit_bg.gif",
    "app/assets/images/admin/subnav_bg.gif",
    "app/assets/images/openid_icon.png",
    "app/assets/images/rails.png",
    "app/assets/images/silk/arrow_undo.png",
    "app/assets/images/silk/delete.png",
    "app/assets/images/silk/pencil.png",
    "app/assets/javascripts/admin.js",
    "app/assets/javascripts/admin/actions.js",
    "app/assets/javascripts/admin/comments.js",
    "app/assets/javascripts/admin/common.js",
    "app/assets/javascripts/admin/dashboard.js",
    "app/assets/javascripts/admin/edit-preview.js",
    "app/assets/javascripts/admin/pages.js",
    "app/assets/javascripts/admin/posts.js",
    "app/assets/javascripts/admin/shortcut.js",
    "app/assets/javascripts/application.js",
    "app/assets/javascripts/common.js",
    "app/assets/javascripts/live-comment-preview.js",
    "app/assets/stylesheets/admin.css",
    "app/assets/stylesheets/application.css.scss",
    "app/assets/stylesheets/humanmsg.css",
    "app/assets/stylesheets/login.css",
    "app/controllers/admin/base_controller.rb",
    "app/controllers/admin/comments_controller.rb",
    "app/controllers/admin/dashboard_controller.rb",
    "app/controllers/admin/health_controller.rb",
    "app/controllers/admin/pages_controller.rb",
    "app/controllers/admin/posts_controller.rb",
    "app/controllers/admin/sessions_controller.rb",
    "app/controllers/admin/undo_items_controller.rb",
    "app/controllers/application_controller.rb",
    "app/controllers/archives_controller.rb",
    "app/controllers/comments_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/controllers/posts_controller.rb",
    "app/helpers/admin/navigation_helper.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/date_helper.rb",
    "app/helpers/form_helper.rb",
    "app/helpers/navigation_helper.rb",
    "app/helpers/page_title_helper.rb",
    "app/helpers/posts_helper.rb",
    "app/helpers/tag_helper.rb",
    "app/helpers/url_helper.rb",
    "app/models/comment.rb",
    "app/models/comment_activity.rb",
    "app/models/delete_comment_undo.rb",
    "app/models/delete_page_undo.rb",
    "app/models/delete_post_undo.rb",
    "app/models/page.rb",
    "app/models/post.rb",
    "app/models/stats.rb",
    "app/models/tag.rb",
    "app/models/tagging.rb",
    "app/models/undo_item.rb",
    "app/views/admin/comments/_comment.html.erb",
    "app/views/admin/comments/index.html.erb",
    "app/views/admin/comments/show.html.erb",
    "app/views/admin/dashboard/show.html.erb",
    "app/views/admin/health/index.html.erb",
    "app/views/admin/pages/_form.html.erb",
    "app/views/admin/pages/_page.html.erb",
    "app/views/admin/pages/index.html.erb",
    "app/views/admin/pages/new.html.erb",
    "app/views/admin/pages/show.html.erb",
    "app/views/admin/posts/_form.html.erb",
    "app/views/admin/posts/_post.html.erb",
    "app/views/admin/posts/index.html.erb",
    "app/views/admin/posts/new.html.erb",
    "app/views/admin/posts/show.html.erb",
    "app/views/admin/sessions/new.html.erb",
    "app/views/admin/undo_items/index.html.erb",
    "app/views/archives/index.html.erb",
    "app/views/comments/_comment.html.erb",
    "app/views/layouts/admin.html.erb",
    "app/views/layouts/application.html.erb",
    "app/views/layouts/login.html.erb",
    "app/views/pages/_page.html.erb",
    "app/views/pages/show.html.erb",
    "app/views/posts/_post.html.erb",
    "app/views/posts/index.atom.builder",
    "app/views/posts/index.html.erb",
    "app/views/posts/show.html.erb",
    "autotest/discover.rb",
    "config.ru",
    "config/.gitignore",
    "config/application.rb",
    "config/boot.rb",
    "config/cucumber.yml",
    "config/database.example.yml",
    "config/enki.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/acts_as_taggable_on_steroids.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/enki_ext.rb",
    "config/initializers/exception_notifier.rb",
    "config/initializers/inflections.rb",
    "config/initializers/mime_types.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/initializers/set_chronic_timezone.rb",
    "config/initializers/verification.rb",
    "config/initializers/wrap_parameters.rb",
    "config/routes.rb",
    "db/.gitignore",
    "db/migrate/009_initialize_db.rb",
    "db/migrate/20110709024316_add_indexes.rb",
    "db/seeds.rb",
    "features/admin_dashboard.feature",
    "features/admin_health.feature",
    "features/admin_undo.feature",
    "features/browsing.feature",
    "features/step_definitions/admin.rb",
    "features/step_definitions/browsing.rb",
    "features/step_definitions/factories.rb",
    "features/step_definitions/posts.rb",
    "features/step_definitions/web_steps.rb",
    "features/support/env.rb",
    "features/support/paths.rb",
    "features/support/selectors.rb",
    "lib/acts_as_taggable_on_steroids/CHANGELOG",
    "lib/acts_as_taggable_on_steroids/MIT-LICENSE",
    "lib/acts_as_taggable_on_steroids/README",
    "lib/acts_as_taggable_on_steroids/Rakefile",
    "lib/acts_as_taggable_on_steroids/generators/acts_as_taggable_migration/acts_as_taggable_migration_generator.rb",
    "lib/acts_as_taggable_on_steroids/generators/acts_as_taggable_migration/templates/migration.rb",
    "lib/acts_as_taggable_on_steroids/init.rb",
    "lib/acts_as_taggable_on_steroids/lib/acts_as_taggable.rb",
    "lib/acts_as_taggable_on_steroids/lib/tag_counts_extension.rb",
    "lib/acts_as_taggable_on_steroids/lib/tag_list.rb",
    "lib/acts_as_taggable_on_steroids/lib/tags_helper.rb",
    "lib/acts_as_taggable_on_steroids/test/abstract_unit.rb",
    "lib/acts_as_taggable_on_steroids/test/acts_as_taggable_test.rb",
    "lib/acts_as_taggable_on_steroids/test/database.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/magazine.rb",
    "lib/acts_as_taggable_on_steroids/test/fixtures/magazines.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/photo.rb",
    "lib/acts_as_taggable_on_steroids/test/fixtures/photos.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/post.rb",
    "lib/acts_as_taggable_on_steroids/test/fixtures/posts.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/special_post.rb",
    "lib/acts_as_taggable_on_steroids/test/fixtures/subscription.rb",
    "lib/acts_as_taggable_on_steroids/test/fixtures/subscriptions.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/taggings.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/tags.yml",
    "lib/acts_as_taggable_on_steroids/test/fixtures/user.rb",
    "lib/acts_as_taggable_on_steroids/test/fixtures/users.yml",
    "lib/acts_as_taggable_on_steroids/test/schema.rb",
    "lib/acts_as_taggable_on_steroids/test/tag_list_test.rb",
    "lib/acts_as_taggable_on_steroids/test/tag_test.rb",
    "lib/acts_as_taggable_on_steroids/test/tagging_test.rb",
    "lib/acts_as_taggable_on_steroids/test/tags_helper_test.rb",
    "lib/core_extensions/object.rb",
    "lib/core_extensions/string.rb",
    "lib/enki/config.rb",
    "lib/enki/html5_tags.rb",
    "lib/enki_formatter.rb",
    "lib/tasks/cucumber.rake",
    "lib/tasks/enki.rake",
    "lib/undo_failed.rb",
    "log/.gitignore",
    "public/.htaccess",
    "public/404.html",
    "public/422.html",
    "public/500.html",
    "public/dispatch.cgi",
    "public/dispatch.fcgi",
    "public/dispatch.rb",
    "public/favicon.ico",
    "public/robots.txt",
    "script/cucumber",
    "script/rails",
    "spec/controllers/admin/comments_controller_spec.rb",
    "spec/controllers/admin/dashboard_controller_spec.rb",
    "spec/controllers/admin/health_controller_spec.rb",
    "spec/controllers/admin/pages_controller_spec.rb",
    "spec/controllers/admin/posts_controller_spec.rb",
    "spec/controllers/admin/sessions_controller_spec.rb",
    "spec/controllers/admin/sessions_routing_spec.rb",
    "spec/controllers/admin/undo_items_controller_spec.rb",
    "spec/controllers/archives_controller_spec.rb",
    "spec/controllers/archives_routing_spec.rb",
    "spec/controllers/comments_controller_spec.rb",
    "spec/controllers/pages_controller_spec.rb",
    "spec/controllers/pages_routing_spec.rb",
    "spec/controllers/posts_controller_spec.rb",
    "spec/controllers/posts_routing_spec.rb",
    "spec/helpers/.gitignore",
    "spec/helpers/page_title_helper_spec.rb",
    "spec/helpers/url_helper_spec.rb",
    "spec/lib/slugorize_spec.rb",
    "spec/models/comment_activity_spec.rb",
    "spec/models/comment_spec.rb",
    "spec/models/delete_comment_undo_spec.rb",
    "spec/models/delete_post_undo_spec.rb",
    "spec/models/page_spec.rb",
    "spec/models/post_spec.rb",
    "spec/models/stats_spec.rb",
    "spec/models/tag_spec.rb",
    "spec/models/tagging_spec.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/be_valid_html5.rb",
    "spec/support/be_valid_xhtml.rb",
    "spec/views/admin/comments/index.html_spec.rb",
    "spec/views/admin/comments/show.html_spec.rb",
    "spec/views/admin/dashboard/show.html_spec.rb",
    "spec/views/admin/pages/index.html_spec.rb",
    "spec/views/admin/pages/new.html_spec.rb",
    "spec/views/admin/pages/show.html_spec.rb",
    "spec/views/admin/posts/index.html_spec.rb",
    "spec/views/admin/posts/new.html_spec.rb",
    "spec/views/admin/posts/show.html_spec.rb",
    "spec/views/admin/sessions/new.html_spec.rb",
    "spec/views/admin/undo_items/index.html_spec.rb",
    "spec/views/archives/index.html_spec.rb",
    "spec/views/layouts/admin.html_spec.rb",
    "spec/views/layouts/application.html_spec.rb",
    "spec/views/layouts/login.html_spec.rb",
    "spec/views/pages/show.html_spec.rb",
    "spec/views/posts/index.atom.builder_spec.rb",
    "spec/views/posts/index.html_spec.rb",
    "spec/views/posts/show.html_spec.rb",
    "vendor/assets/javascripts/humanmsg.js",
    "vendor/assets/javascripts/jquery.easing.1.3.js",
    "vendor/assets/javascripts/jquery.form.js",
    "vendor/assets/javascripts/jquery.jfeed.js",
    "vendor/assets/javascripts/jquery.livequery.js"
  ]
  s.homepage = "http://github.com/andyt"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Enki blog engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.2.1"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<pg>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, ["~> 4.2.9"])
      s.add_runtime_dependency(%q<ruby-openid>, [">= 0"])
      s.add_runtime_dependency(%q<rack-openid>, [">= 0"])
      s.add_runtime_dependency(%q<aaronh-chronic>, [">= 0"])
      s.add_runtime_dependency(%q<coderay>, [">= 0"])
      s.add_runtime_dependency(%q<lesstile>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.2"])
      s.add_runtime_dependency(%q<exception_notification>, ["~> 2.5.2"])
      s.add_runtime_dependency(%q<open_id_authentication>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.2.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<pg>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<RedCloth>, ["~> 4.2.9"])
      s.add_dependency(%q<ruby-openid>, [">= 0"])
      s.add_dependency(%q<rack-openid>, [">= 0"])
      s.add_dependency(%q<aaronh-chronic>, [">= 0"])
      s.add_dependency(%q<coderay>, [">= 0"])
      s.add_dependency(%q<lesstile>, [">= 0"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.2"])
      s.add_dependency(%q<exception_notification>, ["~> 2.5.2"])
      s.add_dependency(%q<open_id_authentication>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.2.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<pg>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<RedCloth>, ["~> 4.2.9"])
    s.add_dependency(%q<ruby-openid>, [">= 0"])
    s.add_dependency(%q<rack-openid>, [">= 0"])
    s.add_dependency(%q<aaronh-chronic>, [">= 0"])
    s.add_dependency(%q<coderay>, [">= 0"])
    s.add_dependency(%q<lesstile>, [">= 0"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.2"])
    s.add_dependency(%q<exception_notification>, ["~> 2.5.2"])
    s.add_dependency(%q<open_id_authentication>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
  end
end

